name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-dev[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v1

      - name: Get Tag
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Print Tag
        run: echo "Publishing with tag ${{ env.tag }}"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish Sophios Container 🐳
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_ubuntu_REST
          push: true
          tags: sameeul/sophios:${{ env.tag }}

